name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v1      
        with:
          node-version: 19.x
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: Configure NPM
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm run build
      - name: Perform Version Bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pack
        run: pnpm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "*.tgz"

  Publish:
    needs: [Build]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'anupheaus'
    steps:
      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Setup Environment
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
          registry-url: https://npm.pkg.github.com/
          scope: "@anupheaus"
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: Configure NPM
        run: echo "registry=https://npm.pkg.github.com/@anupheaus" >> .npmrc
      - name: Publish
        run: pnpm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
